# == [Physics Config] ==
#
#
lag_reduction:
  block_destroy: true
  # RECOMMENDED STAGE: true
  # Eliminate flying blocks when they touch the ground.
  block_drop: false
  # RECOMMENDED STAGE: false
  # If set to false, explosions won't drop anything, reducing ground items
  entity_count: true
  # RECOMMENDED STAGE: true
  # Will periodically check and limit the amount of dropped items in the world to reduce lag
explosion_fire: true
# RECOMMENDED STAGE: ---
# Will produce a particle effect for explosions

