# == [Physics Config] ==
#
#
lag_reduction:
  block_destroy: true
  # RECOMMENDED STAGE: true
  # Eliminate flying blocks when they touch the ground.
  block_drop: false
  # RECOMMENDED STAGE: false
  # If set to false, explosions won't drop anything, reducing ground items
explosion_fire: true
# RECOMMENDED STAGE: ---
# Will produce a particle effect for explosions
explosion_trickle: true
# RECOMMENDED STAGE: ---
# Will cause exploding blocks to affect the ones above them

