name: Physics
main: com.rimofthesky.explosion.Physics
version: 1.2.1
description: Realistic explosive block scattering
author: skyrimfan1
commands:
  physics:
    description: Ingenious physical command base
    aliases: physic

  